
path: D:\Projets Professionnels\ORIZONNE\local_env\datas # /home/phillip/Desktop/todays_tutorial/38_yolov8_train_custom_model/code/data  # dataset root dir
train: train\images  # train images (relative to 'path')
val: val\images  # val images (relative to 'path')

# Classes
names : [
    "dog",
    "person",
    "cat",
    "tv",
    "car",
    "meatballs",
    "marinara sauce",
    "tomato soup",
    "chicken noodle soup",
    "french onion soup",
    "chicken breast",
    "ribs",
    "pulled pork",
    "hamburger",
    "cavity",
    "Tulipier",
    "Billet",
    "Billet5000",
    "Billet10000",
    "Tulipier10000",
  ]
  
